apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lidarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'

spec:
  project: homelab

  source:
    repoURL: https://github.com/sle3pyy/Homelab-k3s.git
    targetRevision: main
    path: manifests/lidarr

  destination:
    server: https://kubernetes.default.svc
    namespace: arr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: musicgrabber
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'

spec:
  project: homelab

  source:
    repoURL: https://github.com/sle3pyy/Homelab-k3s.git
    targetRevision: main
    path: manifests/musicgrabber

  destination:
    server: https://kubernetes.default.svc
    namespace: arr

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
