apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'

spec:
  project: homelab

  source:
    repoURL: https://github.com/sle3pyy/Homelab-k3s.git
    targetRevision: main
    path: manifests/media-storage

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
